FORECAST_FROM_FILE = False

DEBUG_DWD_FETCHER = False
DEBUG_PLOTTER = False
DEBUG_SORT_DATA = True
DEBUG_DATA_HANDLER = False
LOCAL_TZ = "Europe/Berlin"



CLOUDS_TITLE = "Clouds"
TEMP_TITLE = "Temperature"
REST_TITLE = "WindVisibility"
