FORECAST_FROM_FILE = True

# TODO: Let this be handled by settings page
FORECAST_DURATION_HRS = float(48.0)

DEBUG_ALL = False

DEBUG_DATA_HANDLER = DEBUG_ALL or False
DEBUG_DWD_FETCHER = DEBUG_ALL or False
DEBUG_PLOTTER = DEBUG_ALL or True
DEBUG_UTILS = DEBUG_ALL or False
DEBUG_DF_UTILS = DEBUG_ALL or False

LOCAL_TZ = "Europe/Berlin"
