FORECAST_FROM_FILE = True
FORECAST_TIME_HRS = 48

DEBUG_ALL = False

DEBUG_DATA_HANDLER = DEBUG_ALL or False
DEBUG_DWD_FETCHER = False
DEBUG_PLOTTER = DEBUG_ALL or True
DEBUG_UTILS = DEBUG_ALL or False
DEBUG_DF_UTILS = DEBUG_ALL or False

LOCAL_TZ = "Europe/Berlin"

